unity/src/project/SteamAudioUnity/Assets/SteamAudio/GameEngineState.cs
Exception: NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition.
Cause: The call to `iplCreateContext` passes static method `LogCallback` which hasn't been annotated with the `MonoPInvokeCallback` attribute.
Fix: Annotate `LogCallback` with the `MonoPInvokeCallback` attribute. Tested with Unity 2018.3.14f1 and IL2CPP, on Windows 64-bit, in two live games.
=> Fixed Unity exception on call to `iplCreateContext`.

unity/src/project/SteamAudioUnity/Assets/SteamAudio/SteamAudioSource.cs
- If there is no AudioListener, Unity will be spamming the console so there is no need for further console spam from Steam Audio
- This is a common situation with VR interaction toolkits like VRTK where the Listener is missing the first frame
=> Add nullcheck to SteamAudioSource component

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs
Unity allows developers to speed up iteration time in Editor with Play Mode options (https://docs.unity3d.com/Manual/ConfigurableEnterPlayMode.html). 
However, currently using any of the two options doesn't work with Steam Audio. This PR addreses this.
Disabling Scene Reload causes the SceneManager.sceneLoaded event to not be fired on initialization. When this option is enabled, OnSceneLoaded has to be called manually. This should address #219 and potentially #225.
Disabling Domain Reload leaves the SceneManager event handlers still subscribed even when SteamAudioManager is destroyed, which can be fixed by explicitly unsubscribing during shutdown.
Tested on Unity 2021.3
=> Fix compatibility with Enter Play Mode options

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/Baker.cs
If the "SteamAudioStaticMesh" is moved inside another game object. the Baker will believe that the object doesn't exist, whereas this scenario is perfectly supported in the SteamAudioManager (example in GetDataAsset(UnityEngine.SceneManagement.Scene scene)) or the SteamAudioProbeBatch.
=> Fix the Baker so it looks for SteamAudioStaticMesh not only at the root of a scene.

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs
When exporting active scene, local to world space convertion was applied twice inside the 'GetVertices' method of the SteamAudioManager for a terrain. This problem only arises if the terrain position is not at 0,0,0, as applying the terrain position in two places makes no difference.
The first time, the terrain position is added (which has been removed in this PR) and the second time the 'terrain.transform.TransformPoint' method is used a few lines down.
=> Fix the GetVertices method for a terrain

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioSource.cs
I've added a reference to SteamAudioSettings so that the singleton getter isn't unnecessarily used in code running every frame.
Here's my profiler showing the problem:
=> [Unity] SteamAudioSource optimized to take the SteamAudioSettings singleton only once

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioDynamicObject.cs, unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs, unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioStaticMesh.cs
During the development of our current game we noticed that the ```LateUpdate``` method of ```SteamAudioManger``` was producing lag spikes of up to 60ms. See screenshot bellow: 
What we did was deep profile and establish that the culprit was the regular call to 
```mCurrentScene.Commit()```
We isolated the call to ```cs mCurrentScene.Commit()``` in it's own method ```CommitScene()``` inside ```SteamAudioManager``` and then called that method in the relevant places of ```SteamAudioDynamicObject``` and ```SteamAudioStaticMesh```
Additionally a ```transform.hasChanged``` was added to ```SteamAudioDynamicObject``` so that changes are only committed if the object has moved this frame.
After this change we did not notice the introduction of any bugs or discrepancies in how the audio was played, …
=> [Unity] Perormance optimizations concerning calling mCurrentScene.Commit(); in LateUpdate

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs
the method [GetPerspectiveCorrection()](https://github.com/Chrisdbhr/steam-audio/blob/v4.5.0/unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs#L196) in [SteamAudioManager](https://github.com/Chrisdbhr/steam-audio/blob/v4.5.0/unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs) is called every [LateUpdate()](https://docs.unity3d.com/ScriptReference/MonoBehaviour.LateUpdate.html) even when perspectiveCorrection is disabled in [SteamAudioSettings](https://github.com/Chrisdbhr/steam-audio/blob/v4.5.0/unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioSettings.cs) and inside it there are multiple calls to [Camera.main](https://docs.unity3d.com/ScriptReference/Camera-mai …
=> [Unity] Performance improvement on SteamAudioManager.GetPerspectiveCorrection

core/doc/build-instructions.rst
Noticed when copy pasting build command.
=> Fix typo in command in build-instructions.rst

core/src/core/phonon.h
Follow-up to #308
`uint8_t*` is used in `IPLHRTFSettings::sofaData` which requires `stdint.h` to be included. This is unnecessary because there's already an unsigned 8 bit type defined: `IPLuint8`
This PR changes the use of `uint8_t` to `IPLuint8*`.
=> Use IPLuint8 instead of uint8_t in phonon.h

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs
Hello,
we found an issue in the unity integration of steam audio that is due to how unity handles the enterplaymode options.
Current flow evaluates the condition that checks the SceneReload to true in all cases, thus considering that the SceneReload is always disabled, even if the project has the default settings ("Enter playmode Options unticked, thus always reload domain and scene).
This is due to the fact that unity write DisableDomainReload and DisableSceneReload flags by default, and requires to first check if the project has the setting "Enter Playmode Options" ticked before considering the flag values.
You can find the fix attached to this pull request.
Thanks for releasing the project as open source !
=> EnterPlayMode Options fix

core/build/dependencies.json
Due to a -Wunused-but-set-variable warning (and -Werror) in flatbuffers/src/flatbuffers/src/idl_gen_rust.cpp:409
get_dependencies.py is apparently aware of the issue but DCMAKE_C[XX]_FLAGS are defined twice in dependencies.json for flatbuffers, the second time apparently overriding the first.
=> Fix get_dependencies.py failing to build flatbuffers (tested on macOS)

core/src/core/api_validation_layer.cpp
Fixes warning: comparison of different enumeration types ('IPLDirectEffectFlags' and 'IPLTransmissionType') [-Wenum-compare] 
Detected on Xcode 15.2
=> Fix incorrect validation

assets/css/application-startup.css, downloads.html, index.html
Important bugs in mobile are fixed where the menu icon doesn't appear due to font-size pushing the container off-screen.
The structure of .app-marketing-grid is fixed where platform images overlap on tablets.
- Enclose` <h1>, <h2>, <h3> `tags of the hero section within a `.hero` class to adapt font size for mobile devices.
- Eliminate offsets and replace them with display flex center + fix images that protrude beyond the column size.
- Some inline styles are removed and moved into CSS classes.
=> FIX mobile and tablet navigation bugs

core/src/core/api_validation_layer.cpp
```
VALIDATE(IPLfloat32, value->dipoleWeight, (0.0f <= value->dipoleWeight && 1.0f <= value->dipoleWeight)); \
``` 
is intended to ensure the value is between 0 & 1, but as is, it is testing if the value is greater than or equal to 0 & also greater than or equal to 1.
=> Fix Broken DipoleWeight Validation

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/FMODStudioAudioEngineSource.cs
Currently, the `eventInstance != mEventInstance` check always returns true, causing `mFoundDSP` to be set to false for every emitter, each frame.
As a result `FindDSP()` runs past the guard clause for every emitter in the main `Update()` loop. This creates kBs worth of garbage and performance losses with just a handful of audio sources.
Observed in Unity 2022.3.4f1, FMOD 2.01.07, and both Steam Audio 4.1.2 and 4.5.3
After changing `eventInstance != mEventInstance` to `!eventInstance.Equals(mEventInstance)`, `mFoundDSP` remains true until either the fmodEventEmitter changes, or the underlying fmodEventInstance changes (which I assume is the intended behavior).
Tested in Unity 2022.3.4f1, FMOD 2.01.07, and Steam Audio 4.5.3
=> Fixed FMODStudioAudioEngineSource losing DSP every frame

unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioSpatialization.cpp
It was possible to crash the editor because the SteamAudioSourceComponent had no valid owner. So I added a check for it.
=> Fixed Crash because component owner can be invalid.

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs
Selecting "Export Dynamic Object as OBJ" in the Dynamic Object settings in the unity plugin and immediately cancelling the file dialog will crash the editor. Unity returns an empty string if the file dialog is cancelled, which steam audio then tries exporting to which causes undefined behaviour.
This PR simply adds checks to see if the directory is invalid and returns early.
It may also be worth adding checks on the C++ side, currently there are no checks on the file pointers returned by `utf8fopen` on line 291 & 294 of `scene.cpp` which seems to be the root cause of this issue.
=> [Unity] Fix editor crash when cancelling the export OBJ dialog

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs
Can happen when other plugins interacts with the mesh/sharedmesh. For example it's common for the ProBuilder prefabs. They throw errors every time you select them in the project view, since they have a mesh but no shared mesh.
=> [Unity] Fix for when having SteamAudioGeometry on an gameobject that had a mesh but no sharedmesh

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioBakedListener.cs, unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioBakedSource.cs, unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/UnityAudioEngineState.cs
A simple patch to address compiler warnings generated in recent versions of Unity.
The Unity API has marked some methods that are being called by the Steam Audio Unity plugin as obsolete. The following method calls have been changed in this pull request:
- `UnityEngine.Object`: `FindObjectOfType<T>()` replaced with `FindFirstObjectByType<T>()`
- `UnityEngine.Object`: `FindObjectsOfType<T>()` replaced with `FindObjectsByType<T>(FindObjectsSortMode)`
These new methods have been implemented since Unity 2020.3, and the old methods have been marked as obsolete since 2023.1
To ensure compatibility of the Unity plugin remains the same as before (2017.3+), these call changes have been wrapped in `#if UNITY_2020_3_OR-NEWER` preprocessor directives.
This is my first pull request for this repo, let …
=> [Unity] Replace obsoleted Unity API calls

core/src/core/profiler.h
Hello, I am the maintainer of vcpkg. 
Due to the adjustment of `STL` methods, after the PR: https://github.com/microsoft/STL/pull/5105 the call to `std::chrono` needs to explicitly include the header file `chrono`. 
I have submitted a PR in vcpkg to adapt.
https://github.com/microsoft/vcpkg/pull/43670
Error:
```
D:\b\steam-audio\src\ba4a490a67-27c1a63d4c.clean\core\src\core\profiler.h(40): error C2039: 'high_resolution_clock': is not a member of 'std::chrono'
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34433\include\__msvc_chrono.hpp(286): note: see declaration of 'std::chrono'
D:\b\steam-audio\src\ba4a490a67-27c1a63d4c.clean\core\src\core\profiler.h(40): error C2065: 'high_resolution_clock': undeclared identifier …
```
=> Fix std::chrono by include chrono

core/src/core/radeonrays_reflection_simulator.cl
Hi, Valve Team
This is a minor addition to the codebase of the Steam Audio SDK.  All of the `#define` constants at the top of the `radeonrays_reflection_simulator.cl` file now have comments added to them.
I saw that these constants didn't have comments, and it would be very helpful for anyone (including myself in the future!) trying to understand or improve this code to know what these values mean and their units.  I add comments to every one of them. To make sure the comments were accurate, I went over the code.
There are no changes to code functionality; the modifications are only to the documentation in `radeonrays_reflection_simulator.cl`. 
I've never contributed to Valve before and wanted to start small before expanding out. I'm excited to help with the Steam Audio SDK.  Thank you …
=> Docs: Add comments to #define constants in radeonrays_reflection_simulator.cl for improved clarity

unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/UnityAudioEngineSource.cs
mAudioSource can be nuked before the Steam Audio component. 
This handles that and allows Steam Audio to remove the source.
I would also add a debug logerror and potentially reorder this to do the Steam Audio remove source first. 
The fact that UpdateParameters checks this, but on destroy does not make me believe this was missed.
=> adding a null check to destroy in UnityAudioEngineSource.cs

fmod/doc/api-reference.rst, fmod/include/phonon/phonon.h, fmod/src/mix_return_effect.cpp, fmod/src/reverb_effect.cpp, fmod/src/spatialize_effect.cpp, fmod/src/steamaudio_fmod.h
Fully fixes #432 
https://github.com/ValveSoftware/steam-audio/commit/cc661206e341241a2814606c1dbb2957c93119df was a partial fix that didn't fix the root issue, which is that `SteamAudioFMOD::SpatializeEffect::Params`, `SteamAudioFMOD::ReverbEffect::Params`, and `SteamAudioFMOD::MixerReturnEffect::Params` aren't defined in a header anywhere
I moved those enums into `steamaudio_fmod.h` in a C-compatible way so tools like [bindgen](https://github.com/rust-lang/rust-bindgen) can understand them
=> Define DSP parameters in steamaudio_fmod.h

unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioReverb.cpp
When adding Reverb Submix to the Steam Audio settings, if the game starts, the engine crashes. This happens because the `ReverbPlugin` pointer is nullptr. This PR completely fixes this crash.
This problem was also described in issue #405 by @ViniCortez
Also, this problem (looking at Crash Dump) was encountered in #364 
Video demonstrating the crash:
https://github.com/user-attachments/assets/e6f2e6de-8361-4ef8-8755-e8d851a01b0a
=> [Unreal] Fix Adding Reverb Submix to the steam audio settings crash

unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioManager.cpp
Fix a logical error in SteamAudioManager.cpp prevents OpenCL devices from ever being utilized. 
This can cause the `AsyncPool()` function to crash when "TrueAudio Next" is enabled.
=> [Unreal] Fix OpenCL devices are never utilized

unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioManager.cpp, unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioManager.h, unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioOcclusion.cpp, unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioReverb.cpp, unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioSpatialization.cpp
This PR adds the ability to enable or disable Steam Audio during gameplay. This is implemented through the `SetSteamAudioEnabled` function of the `FSteamAudioManager` class.
There were also some requests on the forums to add this feature:
https://steamcommunity.com/app/596420/discussions/0/4035852798886107497
Video demonstrating the feature:
https://github.com/user-attachments/assets/bc68d516-9b90-4aba-af88-45be31cd410b
=> [Unreal] Added the ability to turn off/on Steam Audio dynamically

unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioManager.cpp, unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioManager.h
Without this nullptr check, using TrueAudio Next with not initializing the OpenCL device causes the `AsyncPool()` function to crash.
=> [Unreal] Add nullptr check for OpenCL device

unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Private/SteamAudioSettings.cpp, unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudio/Public/SteamAudioSettings.h, unreal/src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudioEditor/Private/SteamAudioEditorModule.cpp
Adding a Steam Audio Geometry component to an actor requires that you pick one of the Steam Audio Materials for that actor, unless you want to use the default material. This makes the "Add Steam Audio Geometry Component to all actors" less useful, because you still need to set the material for every actor. The thing is, in Unreal we have already set physical materials for all of the actors. It feels silly to have to say "this mesh is brick, and hey Steam, this mesh is brick".
This PR adds a TMap `PhysMatToSteamAudioMatTable` to the plugin settings, where the `Key` is the physical material and the `Value` is the Steam Audio Material.
This PR also adds the ability to select a "default" Steam Audio Material when adding a Geometry Component to All Actors. This means that for all actors whose …
=> [Unreal] Add the ability to map physical materials to Steam Audio Materials
